apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: app
data:

  APP_PORT: "3000"
  APP_DEBUG: "true"

  DB_HOST: postgres
  DB_PORT: "5432"
  DB_DATABASE: postgresdb
  DB_USERNAME: admin
  DB_PASSWORD: psltest

  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_PASSWORD: redis-password
  REDIS_DB: "0"
